services:
  phpfpm:
    image: itkdev/php8.4-fpm:latest
    environment:
      - DRUSH_OPTIONS_URI=https://${COMPOSE_DOMAIN}
      - PHP_SENDMAIL_PATH=/usr/bin/msmtp --host=mail --port=1025 --read-recipients

  nginx:
    labels:
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
     - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
