services:
  phpfpm:
    image: itkdev/php8.4-fpm:latest

  nginx:
    labels:
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
     - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
