<?php

declare(strict_types=1);

namespace Drupal\filmfolk\Plugin\Field\FieldWidget;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Field\Attribute\FieldWidget;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\filmfolk\Plugin\Field\FieldType\FunktionErfaringItem;
use Drupal\taxonomy\Entity\Term;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Defines the 'filmfolk_funktion_erfaring' field widget.
 */
#[FieldWidget(
  id: 'filmfolk_funktion_erfaring',
  label: new TranslatableMarkup('funktion_erfaring'),
  field_types: ['filmfolk_funktion_erfaring'],
)]
final class FunktionErfaringWidget extends WidgetBase {
  use StringTranslationTrait;

  public function __construct(
    $plugin_id,
    $plugin_definition,
    FieldDefinitionInterface $field_definition,
    array $settings,
    array $third_party_settings,
    EntityTypeManagerInterface $entityTypeManager,
  ) {
    parent::__construct($plugin_id, $plugin_definition, $field_definition, $settings, $third_party_settings);
  }

  /**
   *
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
    $plugin_id,
    $plugin_definition,
    $configuration['field_definition'],
    $configuration['settings'],
    $configuration['third_party_settings'],
    $container->get('entity_type.manager')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state): array {
    $element[FunktionErfaringItem::PROPERTY_FUNKTION] = [
      '#type' => 'select',
      '#title' => $this->t('Funktion'),
      '#required' => $element['#required'],
      '#empty_value' => '',
      '#options' => array_map(static fn (Term $term) => $term->label(), $this->loadTerms('funktion')),
      '#default_value' => $items[$delta]->get(FunktionErfaringItem::PROPERTY_FUNKTION)->getString() ?? NULL,
    ];

    $element[FunktionErfaringItem::PROPERTY_ERFARING] = [
      '#type' => 'select',
      '#title' => $this->t('Erfaring'),
      '#required' => $element['#required'],
      '#options' => array_map(static fn (Term $term) => $term->label(), $this->loadTerms('erfaring')),
      '#empty_value' => '',
      '#default_value' => $items[$delta]->get(FunktionErfaringItem::PROPERTY_ERFARING)->getString() ?? NULL,
    ];

    return $element;
  }

  /**
   *
   */
  public function extractFormValues(FieldItemListInterface $items, array $form, FormStateInterface $form_state) {
    // @todo Change the autogenerated stub
    return parent::extractFormValues($items, $form, $form_state);
  }

  /**
   * Load terms.
   *
   * @return array<int, Term>
   */
  private function loadTerms(string $vocabulary): array {
    $storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
    $ids = $storage
      ->getQuery()
      ->accessCheck()
      ->condition('vid', $vocabulary)
      ->sort('weight')
      ->execute();

    return $storage->loadMultiple($ids);
  }

}
