title: Filmfolk

# Theme
remote-theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme

# Environment configurations for showing different Urls depening on the context.
environments_contexts:
  - name: production
    url: https://www.filmfolk.dk
    label: Production
  - name: staging
    url: https://staging.filmfolk.dk
    label: Staging
  - name: test
    url: https://test.filmfolk.dk
    label: Test

# Default environment
default_environment_context: production

# Enable environment selector in the navigation
show_environment_context_selector: true
