title: Filmfolk

# Theme
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme
  -

# Configure callouts for Just-the-docs theme
# Common kinds of callouts include highlight, important, new, note, and warning.
callouts:
  note:
    title: Note
    color: purple
  note-title:
    color: purple
  warning:
    title: Warning
    color: yellow
  warning-title:
    color: yellow
  danger:
    title: Danger
    color: red
  danger-title:
    color: red
  important:
    title: Important
    color: blue
  important-title:
    color: blue

# Environment configurations for showing different Urls depening on the context.
environments_contexts:
  - name: production
    url: https://www.filmfolk.dk
    label: Production
  - name: staging
    url: https://staging.filmfolk.dk
    label: Staging
  - name: test
    url: https://test.filmfolk.dk
    label: Test

# Default environment
default_environment_context: production

# Enable environment selector in the navigation
show_environment_context_selector: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
