on:
  push:
    tags:
      - "*.*.*"

name: Create Github Release

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        run: |
          docker network create frontend
          # Using --classmap-authoritative will break Drupal
          # ('Drupal\mysql\Driver\Database\mysql\Connection' not found), cf.
          # https://getcomposer.org/doc/articles/autoloader-optimization.md#trade-offs-2
          docker compose run --rm --user=root phpfpm composer install --no-dev --optimize-autoloader
          docker compose run --rm --user=root phpfpm composer clear-cache

      # Note: We don't need to build thmee assets

      - name: Clean up
        run: |
          sudo chown -R runner:runner ./

      - name: Make assets dir
        run: |
          mkdir -p ../assets

      - name: Create archive
        run: |
          tar --exclude='.git' -zcf ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz ./

      - name: Create checksum
        run: |
          cd ../assets
          sha256sum ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz > ../assets/checksum.txt

      - name: Create a release in GitHub and uploads assets
        run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes ../assets/*.*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
